### ISSUE TITLE
Add an env var to keep the temp files

### ISSUE THREAD

**Issue by yxsamliu** [RadeonOpenCompute/ROCm-OpenCL-Driver#2]
It is pretty inconvenient to debug the compiler without a way to keep the temp files generated during the compilation. Can we add an env var to keep the temp files? Then we can simply rerun the command dumped by CC_PRINT_OPTIONS=1 to repeat the compilation steps.

Thanks.

**Comment by emankov** [comment]
Done. SHA-1: cb13e4a9
