### ISSUE TITLE
Debug output for different compilation phases 

### ISSUE THREAD

**Issue by kasaurov** [RadeonOpenCompute/ROCm-OpenCL-Driver#26]
In AMDGPUCompiler class there is private variable debug, which controls debug output in InvokeDriver() and InvokeTool(). It worked for me some time ago, but doesn't work at the moment. It is a rather useful functionality for tracking the arguments passed to different compilation phases. It would be great to:
1) Have it working again
2) Have a more convenient way of setting it rather than changing the sources 
3) Add corresponding code to implement this functionality for in-process as well

**Comment by emankov** [comment]
Finally implemented by https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/commit/7f0006aaeae457a32ed9a4f8aaa7d948998ecf73 and https://github.com/RadeonOpenCompute/ROCm-OpenCL-Driver/commit/1ac768ac13def8f44cf038ab4a5d97eed5660da4.
