### ISSUE TITLE
AMDGPUCompilerTest.CompileAndLinkExecutable_File_To_File fails

### ISSUE THREAD

**Issue by dmikushin** [RadeonOpenCompute/ROCm-OpenCL-Driver#80]
Am using LLVM @ 5a98ec95f7c37662aa7bee3d5c5b81f832cc138c (branch "amd-common"):

```
dmikushin@nekkar:~/apc/rocm/ROCm-OpenCL-Driver/build$ src/unittest/roc-cl-unittest 
Running main() from /home/dmikushin/apc/rocm/ROCm-OpenCL-Driver/build/src/unittest/googletest-prefix/src/googletest/googletest/src/gtest_main.cc
[==========] Running 25 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 25 tests from AMDGPUCompilerTest
[ RUN      ] AMDGPUCompilerTest.OutputEmpty
[       OK ] AMDGPUCompilerTest.OutputEmpty (2 ms)
[ RUN      ] AMDGPUCompilerTest.CompileToLLVMBitcode_File_To_File
[       OK ] AMDGPUCompilerTest.CompileToLLVMBitcode_File_To_File (83 ms)
[ RUN      ] AMDGPUCompilerTest.CompileToLLVMBitcode_Buffer_To_Buffer
[       OK ] AMDGPUCompilerTest.CompileToLLVMBitcode_Buffer_To_Buffer (57 ms)
[ RUN      ] AMDGPUCompilerTest.CompileToLLVMBitcode_Include_I1
[       OK ] AMDGPUCompilerTest.CompileToLLVMBitcode_Include_I1 (72 ms)
[ RUN      ] AMDGPUCompilerTest.CompileToLLVMBitcode_Include_I2
[       OK ] AMDGPUCompilerTest.CompileToLLVMBitcode_Include_I2 (69 ms)
[ RUN      ] AMDGPUCompilerTest.CompileAndLinkExecutable_File_To_File
LLVM ERROR: Attempting to emit FLAT_STORE_DWORD_ci instruction but the Feature_isCIOnly predicate(s) are not met
```

**Comment by emankov** [comment]
What was the GPU?

**Comment by emankov** [comment]
It is Hawaii, and it is CI, looks like should work. So, adding guys who may find out the cause.

**Comment by emankov** [comment]
According to the current ROCm [Readme](https://github.com/RadeonOpenCompute/ROCm/blob/master/README.md#supported-gpus) the following list of GPUs are enabled in the ROCm software, though full support is not guaranteed:
•GFX7 GPUs "Hawaii" chips, such as the AMD Radeon R9 390X and FirePro W9100.

So your FirePro W9100 is not fully supported and as long as currently there is no such a task close the ticket.

**Comment by dmikushin** [comment]
Thank you @emankov for spending 2 weeks working on developing this answer! @jlgreathouse this is exactly what I've meant in https://github.com/RadeonOpenCompute/ROCm/issues/640#issuecomment-453717979 Your answer was generous, but your outsources are too lazy to match it.
